config/routes.rb
    match '/roadmap' => 'versions#index', via: :get

    resources :news, only: [:index, :new, :create]

    namespace :time_entries do
      resource :report, controller: 'reports', only: [:show]
    end
    resources :time_entries, controller: 'timelog'

    # Match everything to be the ID of the wiki page except the part that
    # is reserved for the format. This assumes that we have only two formats:
    # .txt and .html
    resources :wiki,
              constraints: { id: /([^\/]+(?=\.txt|\.html)|[^\/]+)/ },
              except: [:index, :create] do
      collection do
        post '/new' => 'wiki#create', as: 'create'
        get :export
        get :date_index
        post :preview
        get '/index' => 'wiki#index'
      end

      member do
        get '/new' => 'wiki#new_child', as: 'new_child'
        get '/diff/:version/vs/:version_from' => 'wiki#diff', as: 'wiki_diff_compare'
        get '/diff(/:version)' => 'wiki#diff', as: 'wiki_diff'
        get '/annotate/:version' => 'wiki#annotate', as: 'wiki_annotate'
        get '/toc' => 'wiki#index'
        match :rename, via: [:get, :patch]
        get :parent_page, action: 'edit_parent_page'
        patch :parent_page, action: 'update_parent_page'
        get :history
        post :protect
        post :add_attachment
        get :list_attachments
        get :select_main_menu_item, to: 'wiki_menu_items#select_main_menu_item'
        post :replace_main_menu_item, to: 'wiki_menu_items#replace_main_menu_item'
        post :preview
      end
    end

    resources :project_associations, controller: 'project_associations' do
      get :confirm_destroy, on: :member
      get :available_projects, on: :collection
    end

    resources :reportings, controller: 'reportings' do
      get :confirm_destroy, on: :member
    end

    resources :timelines, controller: 'timelines' do
      get :confirm_destroy, on: :member
    end

    # as routes for index and show are swapped
    # it is necessary to define the show action later
    # than any other route as it otherwise would
    # work as a catchall for everything under /wiki
    get 'wiki' => 'wiki#show'

    namespace :work_packages do
      resources :calendar, controller: 'calendars', only: [:index]
    end

    resources :work_packages, only: [] do
      collection do
        get '/report/:detail' => 'work_packages/reports#report_details'
        get '/report' => 'work_packages/reports#report'
      end

      # states managed by client-side routing on work_package#index
      get '(/*state)' => 'work_packages#index', on: :collection, as: ''
      get '/create_new' => 'work_packages#index', on: :collection, as: 'new_split'
      get '/new' => 'work_packages#index', on: :collection, as: 'new'

      # state for show view in project context
      get '(/*state)' => 'work_packages#show', on: :member, as: ''
    end

    resources :activity, :activities, only: :index, controller: 'activities'

    resources :boards do
      member do
        get :confirm_destroy
        get :move
        post :move
      end
    end

    resources :categories, except: [:index, :show], shallow: true

    resources :members, only: [:index, :create, :update, :destroy], shallow: true do
      collection do
        get :paginate_users
        match :autocomplete_for_member, via: [:get, :post]
      end
    end

    resource :repository, controller: 'repositories', except: [:new] do
      get :edit # needed as show is configured manually with a wildcard

      # Destroy uses a get request to prompt the user before the actual DELETE request
      get :destroy_info
      get :committers
      post :committers
      get :graph
      get :revisions

      get '/statistics', action: :stats, as: 'stats'

      get '(/revisions/:rev)/diff.:format', action: :diff
      get '(/revisions/:rev)/diff(/*path)', action: :diff,
                                            format: false

      get '(/revisions/:rev)/:format/*path', action: :entry,
                                             format: /raw/,
                                             rev: /[\w0-9\.\-_]+/

      %w{diff annotate changes entry browse}.each do |action|
        get "(/revisions/:rev)/#{action}(/*path)",
            format: 'html',
            action: action,
            constraints: { rev: /[\w0-9\.\-_]+/, path: /.*/ },
            as: "#{action}_revision"
      end

      get '/revision(/:rev)', rev: /[\w0-9\.\-_]+/,
                              action: :revision,
                              as: 'show_revision'

      get '(/revisions/:rev)(/*path)', action: :show,
                                       format: 'html',
                                       constraints: { rev: /[\w0-9\.\-_]+/, path: /.*/ },
                                       as: 'show_revisions_path'
    end
  end

  resources :admin, controller: :admin, only: :index do
    collection do
      get :plugins
      get :info
      post :force_user_language
      post :test_email
    end
  end

  scope 'admin' do
    resource :announcements, only: [:edit, :update]
    constraints(Enterprise) do
      resource :enterprise, only: [:show, :create, :destroy]
    end
    resources :enumerations

    delete 'design/logo' => 'custom_styles#logo_delete', as: 'custom_style_logo_delete'
    delete 'design/favicon' => 'custom_styles#favicon_delete', as: 'custom_style_favicon_delete'
    delete 'design/touch_icon' => 'custom_styles#touch_icon_delete', as: 'custom_style_touch_icon_delete'
    get 'design/upsale' => 'custom_styles#upsale', as: 'custom_style_upsale'
    post 'design/colors' => 'custom_styles#update_colors', as: 'update_design_colors'
    resource :custom_style, only: [:update, :show, :create], path: 'design'

    resources :attribute_help_texts, only: %i(index new create edit update destroy)

    resources :groups do
      member do
        get :autocomplete_for_user
        # this should be put into it's own resource
        match '/members' => 'groups#add_users', via: :post, as: 'members_of'
        match '/members/:user_id' => 'groups#remove_user', via: :delete, as: 'member_of'
        # this should be put into it's own resource
        match '/memberships/:membership_id' => 'groups#edit_membership', via: :put, as: 'membership_of'
        match '/memberships/:membership_id' => 'groups#destroy_membership', via: :delete
        match '/memberships' => 'groups#create_memberships', via: :post, as: 'memberships_of'
      end
    end

    resources :roles, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection do
        put '/' => 'roles#bulk_update'
        get :report
      end
    end

    resources :auth_sources, :ldap_auth_sources do
      member do
        get :test_connection
      end
    end
  end

  # We should fix this crappy routing (split up and rename controller methods)
  get '/settings' => 'settings#index'
  scope 'settings', controller: 'settings' do
    match 'edit', action: 'edit', via: [:get, :post]
    match 'plugin/:id', action: 'plugin', via: [:get, :post]
  end

  # We should fix this crappy routing (split up and rename controller methods)
  get '/workflows' => 'workflows#index'
  scope 'workflows', controller: 'workflows' do
    match 'edit', action: 'edit', via: [:get, :post]
    match 'copy', action: 'copy', via: [:get, :post]
  end

  namespace :work_packages do
    match 'auto_complete' => 'auto_completes#index', via: [:get, :post]
    resources :calendar, controller: 'calendars', only: [:index]
    resource :bulk, controller: 'bulk', only: [:edit, :update, :destroy]
    # FIXME: this is kind of evil!! We need to remove this soonest and
    # cover the functionality. Route is being used in work-package-service.js:331
    get '/bulk' => 'bulk#destroy'
  end

  resources :work_packages, only: [:index] do
    get :column_data, on: :collection # TODO move to API

    # move bulk of wps
    get 'move/new' => 'work_packages/moves#new', on: :collection, as: 'new_move'
    post 'move' => 'work_packages/moves#create', on: :collection, as: 'move'
    # move individual wp
    resource :move, controller: 'work_packages/moves', only: [:new, :create]

    # this duplicate mapping is required for the timelog_helper
    namespace :time_entries do
      resource :report, controller: 'reports'
    end
    resources :time_entries, controller: 'timelog'

    # states managed by client-side routing on work_package#index
    get 'details/*state' => 'work_packages#index', on: :collection, as: :details

    # states managed by client-side (angular) routing on work_package#show
    get '/' => 'work_packages#index', on: :collection, as: 'index'
    get '/create_new' => 'work_packages#index', on: :collection, as: 'new_split'
    get '/new' => 'work_packages#index', on: :collection, as: 'new', state: 'new'
    get '(/*state)' => 'work_packages#show', on: :member, as: ''
    get '/edit' => 'work_packages#show', on: :member, as: 'edit'
  end

  resources :versions, only: [:show, :edit, :update, :destroy] do
    member do
      get :status_by
    end
  end

  namespace :time_entries do
    resource :report, controller: 'reports',
                      only: [:show]
  end

  resources :time_entries, controller: 'timelog'

  resources :activity, :activities, only: :index, controller: 'activities'

  resources :users do
    resources :memberships, controller: 'users/memberships', only: [:update, :create, :destroy]

    member do
      match '/edit/:tab' => 'users#edit', via: :get, as: 'tab_edit'
      match '/change_status/:change_action' => 'users#change_status_info', via: :get, as: 'change_status_info'
      post :change_status
      post :resend_invitation
      get :deletion_info
    end
  end

  resources :boards, only: [] do
    resources :topics, controller: 'messages', except: [:index], shallow: true do
      member do
        get :quote
        post :reply, as: 'reply_to'
        post :preview
      end

      post :preview, on: :collection
    end
  end

app/models/repository/git.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2017 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2017 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

require 'open_project/scm/adapters/git'

class Repository::Git < Repository
  validates_presence_of :url
  validate :validity_of_local_url

  def self.scm_adapter_class
    OpenProject::Scm::Adapters::Git
  end

  def configure(scm_type, _args)
    if scm_type == self.class.managed_type
      unless manageable?
        raise OpenProject::Scm::Exceptions::RepositoryBuildError.new(
          I18n.t('repositories.managed.error_not_manageable')
        )
      end

      self.root_url = managed_repository_path
      self.url = managed_repository_url
    end
  end

  def self.permitted_params(params)
    super(params).merge(params.permit(:path_encoding))
  end

  def self.supported_types
    types = [:local]
    types << managed_type if manageable?

    types
  end

  def managed_repo_created
    scm.initialize_bare_git
  end

  def repository_identifier
    "#{super}.git"
  end

  def repository_type
    'Git'
  end

  ##
  # Git doesn't like local urls when visiting
  # the repository, thus always use the path.
  def managed_repository_url
    managed_repository_path
  end

  def supports_directory_revisions?
    true
  end

  def repo_log_encoding
    'UTF-8'
  end

  def self.authorization_policy
    ::Scm::GitAuthorizationPolicy
  end

  # Returns the identifier for the given git changeset
  def self.changeset_identifier(changeset)
    changeset.scmid
  end

  # Returns the readable identifier for the given git changeset
  def self.format_changeset_identifier(changeset)
    format_revision(changeset.revision)
  end

  def self.format_revision(revision)
    revision[0, 8]
  end

  def branches
    scm.branches
  end

  def tags
    scm.tags
  end

  def find_changeset_by_name(name)
    return nil if name.nil? || name.empty?
    e = changesets.where(['revision = ?', name.to_s]).first
    return e if e
    changesets.where(['scmid LIKE ?', "#{name}%"]).first
  end

  # With SCM's that have a sequential commit numbering, redmine is able to be
  # clever and only fetch changesets going forward from the most recent one
  # it knows about.  However, with git, you never know if people have merged
  # commits into the middle of the repository history, so we should parse
  # the entire log. Since it's way too slow for large repositories, we only
  # parse 1 week before the last known commit.
  # The repository can still be fully reloaded by calling #clear_changesets
  # before fetching changesets (eg. for offline resync)
  def fetch_changesets
    c = changesets.order('committed_on DESC').first
    since = (c ? c.committed_on - 7.days : nil)

    revisions = scm.revisions('', nil, nil, all: true, since: since, reverse: true)
    return if revisions.nil? || revisions.empty?

    recent_changesets = changesets.where(['committed_on >= ?', since])

    # Clean out revisions that are no longer in git
    recent_changesets.each do |c| c.destroy unless revisions.detect { |r| r.scmid.to_s == c.scmid.to_s } end

    # Subtract revisions that redmine already knows about
    recent_revisions = recent_changesets.map(&:scmid)
    revisions.reject! do |r| recent_revisions.include?(r.scmid) end

    # Save the remaining ones to the database
    unless revisions.nil?
      revisions.each do |rev|
        transaction do
          changeset = Changeset.new(
            repository: self,
            revision:   rev.identifier,
            scmid:      rev.scmid,
            committer:  rev.author,
            committed_on: rev.time,
            comments:   rev.message)

          if changeset.save
            rev.paths.each do |file|
              Change.create(
                changeset: changeset,
                action:    file[:action],
                path:      file[:path])
            end
          end
        end
      end
    end
  end

  def latest_changesets(path, rev, limit = 10)
    revisions = scm.revisions(path, nil, rev, limit: limit, all: false)
    return [] if revisions.nil? || revisions.empty?

    changesets.where(['scmid IN (?)', revisions.map!(&:scmid)])
      .order('committed_on DESC')
  end

  private

  def validity_of_local_url
    parsed = URI.parse root_url.presence || url
    if parsed.scheme == 'ssh'
      errors.add :url, :must_not_be_ssh
    end
  rescue => e
    Rails.logger.error "Failed to parse repository url for validation: #{e}"
    errors.add :url, :invalid_url
  end
end

app/views/repositories/_breadcrumbs.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%= link_to({ action: 'show', project_id: @project, path: nil, rev: @rev },
            { title: I18n.t(:label_repository_root) }) do %>
  <%= op_icon('icon-home repository-breadcrumbs--home') %>
<% end %>
<%
dirs = path.split('/')
link_path = ''
dirs.each_with_index do |dir, index|
    next if dir.blank?
    link_path << '/' unless link_path.empty?
    link_path << "#{dir}"
    %>
    <span class="repository-breadcrumbs--sep"></span>
      <% if index == dirs.size - 1 %>
        <strong><%= h(dir) %></strong>
      <% else %>
        <%= link_to h(dir), action: 'show', project_id: @project,
                            path: to_path_param(link_path), rev: @rev %>
      <% end %>
<% end %>
<%
  # @rev is revsion or git branch or tag.
  rev_text = @changeset.nil? ? @rev : format_revision(@changeset)
%>
<span class="repository-bradcrumbs--identifier">
  <%= "(#{l('repositories.at_identifier', identifier: rev_text)})" if rev_text.present? %>
</span>

<% html_title(h(with_leading_slash(path))) -%>

app/views/repositories/_checkout_instructions.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>
<% if @instructions.available? %>
<div id="repository--checkout-instructions"
     class="notification-box -info persistent-toggle--notification"
     hidden>
  <a title="{{ ::I18n.t('js.close_popup_title') }}"
     class="notification-box--close icon-context icon-close">
  </a>
  <div class="notification-box--content">
    <p>
    <%= simple_format instructions.instructions %>
    <% if instructions.manages_permissions? %>
      <br/>
      <span><%= l('repositories.checkout.access_permission') %>:</span>
      <strong><%= l("repositories.checkout.access.#{instructions.permission}") %></strong>
    <% end %>
    </p>
  </div>
</div>
<% elsif @instructions.supported_but_not_enabled? %>
<div class="notification-box -warning">
  <a title="{{ ::I18n.t('js.close_popup_title') }}"
     class="notification-box--close icon-context icon-close">
  </a>
  <div class="notification-box--content">
    <p><%= l('repositories.checkout.not_available') %></p>
  </div>
</div>
<% end %>

app/views/repositories/_repository_header.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'repository_navigation' %>
<% end %>
<persistent-toggle identifier="repository.checkout_instructions">
<%= toolbar title: l('repositories.named_repository',
                     vendor_name: @repository.class.vendor_name) do %>
  <% if @instructions && @instructions.available? %>
  <li class="toolbar-item toolbar-input-group">
    <div class="toolbar-input-group--affix -prepend">
      <span><%= @instructions.checkout_command %></span>
    </div>
    <input id="repository-checkout-url"
           type="text" class="-clickable" size="40"
           value="<%= @instructions.checkout_url(true) %>"
           onclick="this.focus(); this.select();"
           readonly>
    <button class="toolbar-input--affix toolbar-input-group--affix -append"
            title="<%= l(:label_copy_to_clipboard) %>"
            copy-to-clipboard
            clipboard-target="#repository-checkout-url">
      <%= op_icon('icon-copy') %>
      <span class="hidden-for-sighted"><%= l(:label_copy_to_clipboard) %></span>
    </button>
  </li>
  <li class="toolbar-item -icon-only">
    <a id="repository--checkout-instructions-toggle"
       class="persistent-toggle--click-handler button"
       ng-class="{ '-pressed': !isHidden }"
       title="<%= l('repositories.checkout.show_instructions') %>">
      <%= op_icon('button--icon icon-info1') %>
    </a>
  </li>
  <% end %>
  <% if !empty && User.current.allowed_to?(:browse_repository, @project) %>
  <li class="toolbar-item -icon-only">
    <%= link_to stats_project_repository_path(@project),
        class: 'button', title: l(:label_statistics) do %>
      <%= op_icon('button--icon icon-chart1') %>
    <% end %>
  </li>
  <% end %>
  <%= call_hook(:repositories_navigation_toolbar,
                { repository: @repository, project: @project, repository_empty: empty }) %>
  <% if User.current.allowed_to?(:manage_repository, @project) %>
    <li class="toolbar-item -icon-only">
      <%= link_to settings_project_path(@project, tab: 'repository'),
          class: 'button', title: l(:label_settings) do %>
        <%= op_icon('button--icon icon-settings') %>
      <% end %>
    </li>
  <% end %>
<% end %>


<% if @instructions %>
  <%= render partial: 'checkout_instructions',
             locals: { repository: @repository, instructions: @instructions } %>
<% end %>
</persistent-toggle>

app/views/repositories/annotate.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>
<%= call_hook(:view_repositories_show_contextual, { repository: @repository, project: @project }) %>
<% html_title(l(:button_annotate)) %>
<%= render partial: 'repository_header', locals: { empty: false } %>

<div class="repository-breadcrumbs">
  <%= render partial: 'breadcrumbs',
             locals: { path: @path, revision: @rev }.merge(kind: 'file') %>
</div>
<p><%= render partial: 'link_to_functions' %></p>

<% if @annotate.nil? || @annotate.empty? %>
  <%= no_results_box %>
<% else %>
  <% colors = Hash.new {|k,v| k[v] = (k.size % 12) } %>
  <div class="autoscroll">
    <table class="filecontent annotate CodeRay">
      <tbody>
        <% line_num = 1 %>
        <% syntax_highlight(@path, to_utf8_for_repositories(@annotate.content)) do |line| %>
          <% revision = @annotate.revisions[line_num-1] %>
          <tr class="bloc-<%= revision.nil? ? 0 : colors[revision.identifier || revision.revision] %>">
            <th class="line-num" id="L<%= line_num %>"><a href="#L<%= line_num %>"><%= line_num %></a></th>
            <td class="revision">
              <%= (revision.identifier ? link_to_revision(revision, @project) : format_revision(revision)) if revision %></td>
            <td class="author"><%= h(revision.author.to_s.split('<').first) if revision %></td>
            <td class="line-code">
              <pre><%= line %></pre>
            </td>
          </tr>
          <% line_num += 1 %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/repositories/show.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%= render partial: 'repository_header', locals: { empty: false } %>

<div class="repository-breadcrumbs">
  <%= render partial: 'breadcrumbs',
             locals: { path: @path, revision: @rev }.merge(kind: 'dir') %>
</div>

<% if !@entries.nil? && authorize_for('repositories', 'browse') %>
<%= render partial: 'dir_list' %>
<% end %>

<%= render_properties(@properties) %>

<%= toolbar title: l(:label_revision_plural), html: { class: 'repository--revision-toolbar' } do %>
  <%# rev => nil prevents overwriting the rev parameter queried for in the form with the parameter from the request %>
  <%= form_tag({ action: controller.action_name,
                 project_id: @project,
                 path: to_path_param(@path),
                 rev: nil
               },
               method: :get,
               id: 'revision_selector',
               class: 'form -vertical'
              ) do %>
    <li class="toolbar-item toolbar-input-group">
      <div>
        <%= label_tag 'rev', I18n.t('repositories.go_to_revision') %>
      </div>
      <%= text_field_tag :rev, @rev, id: 'revision-identifier-input', placeholder: l(:label_revision) %>
    </li>
    <% if !@repository.branches.nil? && @repository.branches.length > 0 %>
    <li class="toolbar-item toolbar-input-group">
      <div>
        <%= label_tag 'branch', I18n.t(:label_branch) %>
      </div>
      <%= select_tag :branch, options_for_select([''] + @repository.branches, @rev), id: 'revision-branch-select' %>
    </li>
    <% end %>
    <% if !@repository.tags.nil? && @repository.tags.length > 0 %>
    <li class="toolbar-item toolbar-input-group">
      <div>
        <%= label_tag 'tag', I18n.t(:label_tag) %>
      </div>
      <%= select_tag :tag, options_for_select([''] + @repository.tags, @rev), id: 'revision-tag-select' %>
    </li>
    <% end %>
    <% if User.current.impaired? %>
    <li class="toolbar-item">
      <div>
        <%= button_tag l(:button_submit), type: :submit, class: 'button -highlight' %>
      </div>
    </li>
    <% end %>
    <li class="toolbar-item -icon-only">
      <%= link_to({ url: { action: 'revisions', project_id: @project,
                           key: User.current.rss_key } },
                  { class: 'button', title: l('repositories.atom_revision_feed') }) do %>
        <%= op_icon('button--icon icon-export-atom') %>
      <% end %>
    </li>
  <% end %>
<% end %>

<% if authorize_for('repositories', 'revisions') %>
<%   if @changesets && !@changesets.empty? %>
<%=    render partial: 'revisions',
              locals: {project: @project, path: @path,
                          revisions: @changesets, entry: nil }%>
<%   end %>
<p>
<%
     has_branches = (!@repository.branches.nil? && @repository.branches.length > 0)
     sep = ''
 %>

<%   if @repository.supports_all_revisions? && @path.blank? %>
<%= link_to l(:label_view_all_revisions), revisions_project_repository_path(@project) %>
<%   sep = '|' %>
<%   end %>
</p>
<% end %>

<% html_title(l(:label_repository)) -%>