vendored-plugins/openproject-avatars/config/routes.rb
OpenProject::Application.routes.draw do
  # Update my avatar
  scope 'my' do
    resource :avatar, controller: 'avatars/my_avatar', as: 'edit_my_avatar', only: %i[show update destroy]
  end

  # Get the current avatar
  get '/users/:id/avatar', controller: 'avatars/avatar', action: :show, as: 'user_avatar'

  # Update another user's avatar
  scope 'users/:id' do
    resource :avatar, controller: 'avatars/users', as: 'edit_user_avatar', only: %i[show update destroy]
  end
end

vendored-plugins/openproject-avatars/app/controllers/avatars/avatar_controller.rb
module ::Avatars
  class AvatarController < ::ApplicationController
    before_action :ensure_enabled
    before_action :find_avatar

    def show
      send_file @avatar.diskfile,
                filename: filename_for_content_disposition(@avatar.filename),
                type: @avatar.content_type,
                disposition: 'inline'
    end

    private

    def find_avatar
      @avatar = User.get_local_avatar(params[:id])

      unless @avatar
        render_404
        return false
      end
    end

    def ensure_enabled
      unless ::OpenProject::Avatars::AvatarManager.local_avatars_enabled?
        render_404
      end
    end
  end
end

vendored-plugins/openproject-avatars/app/controllers/avatars/base_controller.rb
module ::Avatars
  class BaseController < ::ApplicationController
    before_action :ensure_enabled

    def update
      if request.put?
        result = service_request(type: :update)
        if result.success?
          render plain: result.result, status: 200
        else
          render plain: result.errors.full_messages.join(", "), status: 400
        end
      else
        head :method_not_allowed
      end
    end

    def destroy
      if request.delete?
        result = service_request(type: :destroy)
        if result.success?
          flash[:notice] = result.result
        else
          flash[:error] = result.errors.full_messages.join(", ")
        end
        redirect_to redirect_path
      else
        head :method_not_allowed
      end
    end

    private

    def redirect_path
      raise NotImplementedError
    end

    def ensure_enabled
      unless ::OpenProject::Avatars::AvatarManager.avatars_enabled?
        render_404
      end
    end

    def service_request(type:)
      service = ::Avatars::UpdateService.new @user

      if type == :update
        service.replace params[:avatar]
      elsif type == :destroy
        service.destroy
      end
    end
  end
end

vendored-plugins/openproject-avatars/app/controllers/avatars/my_avatar_controller.rb
module ::Avatars
  class MyAvatarController < BaseController
    before_action :require_login
    before_action :set_user

    layout 'my'
    menu_item :avatar

    def show
      render 'avatars/my/avatar'
    end

    private

    def redirect_path
      edit_my_avatar_path
    end

    def set_user
      @user = current_user
    end
  end
end

vendored-plugins/openproject-avatars/app/controllers/avatars/users_controller.rb
module ::Avatars
  class UsersController < BaseController
    before_action :require_admin
    before_action :find_user

    layout 'admin', except: :show

    def show
      redirect_to redirect_path
    end

    private

    def redirect_path
      edit_user_path(@user, tab: 'avatar')
    end

    def find_user
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render_404
    end
  end
end

vendored-plugins/openproject-avatars/app/views/avatars/users/_avatar.html.erb
<% @manager = ::OpenProject::Avatars::AvatarManager %>
<% if @manager.gravatar_enabled? %>
    <%= render partial: 'avatars/users/gravatars' %>
<% end %>

<% if @manager.local_avatars_enabled? %>
    <%= render partial: 'avatars/users/local_avatars' %>
<% end %>

vendored-plugins/openproject-avatars/app/views/avatars/users/_avatar_tab.html.erb
<h2><%= t(:button_change_avatar) %></h2>

<% @manager = ::OpenProject::Avatars::AvatarManager %>
<% @target_avatar_path = edit_user_avatar_path(@user) %>
<%= form_tag(edit_user_avatar_path(@user), method: :put, name: 'avatar_form', multipart: true) do %>
  <%= render partial: 'avatars/users/avatar' %>
<% end %>

vendored-plugins/openproject-avatars/app/views/avatars/users/_gravatars.html.erb
<fieldset class="form--fieldset">
  <legend class="form--fieldset-legend" title="<%= t 'avatars.label_gravatar'  %>"><%= t 'avatars.label_gravatar'  %></legend>
  <p>
    <%= t 'avatars.text_your_current_gravatar' %>
  </p>
  <div class="avatars--current-gravatar">
    <%= build_gravatar_image_tag @user %>
  </div>

  <% if @user == current_user %>
    <p>
      <strong><%= t 'note' %></strong>:
      <%= t('avatars.text_change_gravatar_html', gravatar_url: link_to('gravatar.com', 'https://www.gravatar.com')).html_safe %>
    </p>
  <% end %>
</fieldset>

vendored-plugins/openproject-avatars/app/views/avatars/users/_local_avatars.html.erb
<fieldset class="form--fieldset">
  <legend class="form--fieldset-legend" title="<%= t 'avatars.label_local_avatar' %>"><%= t 'avatars.label_local_avatar' %></legend>
  <p>
    <%= t 'avatars.text_your_local_avatar' %>
    <% if @manager.gravatar_enabled? %>
      <br/>
      <%= t 'avatars.text_local_avatar_over_gravatar' %>
    <% end %>
  </p>
    <div class="form--field">
      <label class="form--label" for="username">
        <%= l(:label_current_avatar) %>
      </label>
      <div class="form--field-container">
        <div class="avatars--local-gravatar">
          <div class="avatars--current-local-avatar">
            <% if local_avatar? @user %>
                <%= avatar(@user) %>
            <% else %>
              <%= t :label_none %>
            <% end %>
          </div>
          <% if local_avatar? @user %>
            <%= link_to t(:button_delete),
                        @target_avatar_path,
                        method: :delete,
                        class: 'avatars--local-avatar-delete-link',
                        data: { confirm: t(:are_you_sure_delete_avatar) } %>
          <% end %>
        </div>
      </div>
    </div>
    <avatar-upload-form target="<%= @target_avatar_path %>" method="PUT">
    </avatar-upload-form>
</fieldset>